defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 100

training:
  rec_results_freq: 500
  max_steps : 20000

batch_size:
  IC_boundary: 512
  IC_interior: 2048
  BC: 512
  PDE_interior: 8192